import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <style jsx>
        {`
          h2{
            font-size: 38px; 
          }
          h3{
            font-size:28px;
          }
        `}
      </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            A blog for hunting coders by a hunting coder
          </p>
          <div>
            By Ayush
          </div>
        </div>

        <div className={styles.main2}>
          <h1>Hunting Coder</h1>
        </div>
        <img className={styles.myImg} src="/homeimg.webp" alt="" width={237 * 1.5} height={158 * 1.5} />
        <div className={styles.blog}>
          <h2 className={styles.h2a}>Latest Blogs</h2>
          <div>
            <h3 className={styles.bloghead}>How to learn Javascript in 2023?</h3>
            <p>Javascript is a language used to design the logic of the web</p>
            <button className={styles.btn}>Read More</button>
          </div>
        </div>
        <div className={styles.blog}>
          <div>
            <h3 className={styles.bloghead}>How to learn Next-js in 2023?</h3>
            <p>Next.js is an open-source web development framework created by the private company Vercel providing React-based web applications with server-side rendering and static website generation. </p>
            <button className={styles.btn}>Read More</button>
          </div>
        </div>
        <div className={styles.blog}>
          <div>
            <h3 className={styles.bloghead}>How to learn Flask in 2023?</h3>
            <p>Flask is a Python web framework that provides configuration, conventions, and tools to create and deploy web applications.</p>
            <button className={styles.btn}>Read More</button>
          </div>
        </div>
      </main>
    </>
  )
}
